server:
  port: 8801

spring:
  application:
    name: spring-cloud-alibaba-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://spring-cloud-alibaba-provider
